"""
evaluator_gpt_batch - Evaluator variant using the OpenAI Batch API.

:class:`EvaluatorGptBatch` extends :class:`Evaluator` to submit evaluation
requests in bulk via OpenAI's Batch API, collecting logprobs for YES/NO tokens.
"""

import json
import logging
import os
import time

from dotenv import load_dotenv
from langchain_ollama import ChatOllama
from openai import OpenAI
from openai.types.batch import Batch

from medicalexplainer.dataset import Dataset
from medicalexplainer.evaluator import Evaluator
from medicalexplainer.llm import MODELS
from medicalexplainer.logger import configure_logger
from medicalexplainer.paths import BATCH_REQUESTS_DIR, BATCH_RESULTS_DIR, LOG_PATH

logger = logging.getLogger("evaluator_gpt_batch")


class EvaluatorGptBatch(Evaluator):
    """
    Evaluator that uses the OpenAI Batch API to evaluate answers and obtain
    logprobs for YES/NO responses.
    """

    def __init__(self) -> None:
        """Initialize the batch evaluator with an OpenAI client."""
        super().__init__()
        configure_logger(name="evaluator_gpt_batch", filepath=LOG_PATH)
        load_dotenv()
        self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        self.batch_model = "gpt-4.1-nano"
        logger.info("Initialized EvaluatorGptBatch with model: %s", self.batch_model)

    def create_evaluation_request(
        self,
        custom_id: str,
        question: str,
        answer_llm: str,
        expected_answer: str,
        context: str,
    ) -> dict:
        """
        Create a single evaluation request in the format required by the Batch API.

        Args:
            custom_id (str): Unique identifier for this request.
            question (str): The question to evaluate.
            answer_llm (str): The answer generated by the LLM.
            expected_answer (str): The expected answer from the dataset.
            context (str): The medical context from the dataset.

        Returns:
            dict: A request object formatted for the Batch API.
        """
        prompt = (
            f'Here is a medical question with its context and the answer that was generated by LLM:\n'
            f'Context: "{context}"\n'
            f'Question: "{question}"\n'
            f'Answer LLM: "{answer_llm}"\n'
            f'Compare it with the expected answer:\n'
            f'"{expected_answer}"\n'
            f'Is the answer generated by the LLM almost correct compared to the expected answer?\n'
            f'You ONLY can answer YES/NO'
        )

        return {
            "custom_id": custom_id,
            "method": "POST",
            "url": "/v1/chat/completions",
            "body": {
                "model": self.batch_model,
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a medical expert evaluator. You must respond only with YES or NO.",
                    },
                    {"role": "user", "content": prompt},
                ],
                "max_tokens": 5,
                "temperature": 0,
                "logprobs": True,
                "top_logprobs": 2,
            },
        }

    def create_batch_files(
        self,
        dataset: Dataset,
        model_name: str,
        llm_answers: list[dict],
        max_requests_per_batch: int = 200,
    ) -> list[str]:
        """
        Create JSONL files with evaluation requests, splitting into multiple batches if needed.

        Args:
            dataset (Dataset): The dataset with questions and expected answers.
            model_name (str): Name of the model being evaluated.
            llm_answers (list[dict]): Answers generated by the LLM.
            max_requests_per_batch (int): Maximum requests per batch to avoid token limits.

        Returns:
            list[str]: Paths to the created JSONL files.
        """
        batch_dir = BATCH_REQUESTS_DIR
        batch_dir.mkdir(parents=True, exist_ok=True)

        timestamp = int(time.time())
        total_items = len(dataset.dataset_items)
        num_batches = (total_items + max_requests_per_batch - 1) // max_requests_per_batch

        batch_file_paths: list[str] = []

        for batch_num in range(num_batches):
            start_idx = batch_num * max_requests_per_batch
            end_idx = min(start_idx + max_requests_per_batch, total_items)

            batch_file_path = (
                batch_dir
                / f"batch_{model_name}_{timestamp}_part{batch_num + 1}of{num_batches}.jsonl"
            )

            with open(batch_file_path, "w") as f:
                for idx in range(start_idx, end_idx):
                    item = dataset.dataset_items[idx]
                    llm_answer = llm_answers[idx]

                    request = self.create_evaluation_request(
                        custom_id=f"{model_name}_q{idx}",
                        question=item["question"],
                        answer_llm=llm_answer["final_answer"],
                        expected_answer=item["answer"],
                        context=item["context"],
                    )
                    f.write(json.dumps(request) + "\n")

            logger.info(
                "Created batch file %d/%d: %s (%d requests)",
                batch_num + 1,
                num_batches,
                batch_file_path,
                end_idx - start_idx,
            )
            batch_file_paths.append(str(batch_file_path))

        return batch_file_paths

    def check_batch_capacity(self) -> bool:
        """
        Check whether there are in-progress batches that may be consuming the token quota.

        Returns:
            bool: True if there is available capacity, False if the caller should wait.
        """
        try:
            batches = self.client.batches.list(limit=10)
            in_progress = [
                b
                for b in batches.data
                if b.status in ("validating", "in_progress", "finalizing")
            ]

            if in_progress:
                logger.warning("Found %d batches in progress:", len(in_progress))
                for b in in_progress:
                    logger.warning("  - Batch %s: %s", b.id, b.status)
                return False
            return True
        except Exception as exc:
            logger.error("Error checking batch capacity: %s", exc)
            return True

    def submit_batch(
        self, batch_file_path: str, max_retries: int = 5, retry_delay: int = 300
    ) -> str:
        """
        Upload the batch file to OpenAI and create a batch job.

        Retries automatically if the token limit is exceeded.

        Args:
            batch_file_path (str): Path to the JSONL batch file.
            max_retries (int): Maximum number of retry attempts.
            retry_delay (int): Seconds to wait between retries (default: 5 minutes).

        Returns:
            str: The batch ID.
        """
        with open(batch_file_path, "rb") as f:
            batch_input_file = self.client.files.create(file=f, purpose="batch")

        logger.info("Uploaded batch file with ID: %s", batch_input_file.id)

        for attempt in range(max_retries):
            try:
                if not self.check_batch_capacity():
                    logger.warning(
                        "Token limit may be reached. Waiting %ds before retry %d/%d...",
                        retry_delay,
                        attempt + 1,
                        max_retries,
                    )
                    time.sleep(retry_delay)
                    continue

                batch = self.client.batches.create(
                    input_file_id=batch_input_file.id,
                    endpoint="/v1/chat/completions",
                    completion_window="24h",
                )

                logger.info("Created batch with ID: %s", batch.id)
                return batch.id

            except Exception as exc:
                error_str = str(exc)
                if (
                    "token_limit_exceeded" in error_str
                    or "enqueued token limit" in error_str.lower()
                ):
                    logger.warning(
                        "Token limit exceeded. Attempt %d/%d. Waiting %ds...",
                        attempt + 1,
                        max_retries,
                        retry_delay,
                    )
                    time.sleep(retry_delay)
                else:
                    logger.error("Error creating batch: %s", exc)
                    raise

        raise RuntimeError(
            f"Failed to create batch after {max_retries} retries due to token limit"
        )

    def wait_for_batch_completion(self, batch_id: str, poll_interval: int = 60) -> Batch:
        """
        Wait for a batch to complete, polling at regular intervals.

        Args:
            batch_id (str): The batch ID to monitor.
            poll_interval (int): Seconds to wait between status checks.

        Returns:
            Batch: The completed batch object.
        """
        logger.info("Waiting for batch %s to complete...", batch_id)

        while True:
            batch = self.client.batches.retrieve(batch_id)
            logger.info("Batch %s status: %s", batch_id, batch.status)

            if batch.status == "completed":
                logger.info("Batch %s completed successfully", batch_id)
                logger.debug("Batch output_file_id: %s", batch.output_file_id)
                logger.debug("Batch error_file_id: %s", batch.error_file_id)
                return batch
            elif batch.status in ("failed", "expired", "cancelled"):
                logger.error("Batch %s ended with status: %s", batch_id, batch.status)
                if hasattr(batch, "errors"):
                    logger.error("Batch errors: %s", batch.errors)
                raise RuntimeError(f"Batch failed with status: {batch.status}")

            time.sleep(poll_interval)

    def parse_batch_results(self, batch: Batch) -> list[dict]:
        """
        Download and parse the results from a completed batch.

        Args:
            batch (Batch): The completed batch object.

        Returns:
            list[dict]: List of results with evaluations and logprobs.
        """
        if not batch.output_file_id:
            error_msg = f"Batch {batch.id} has no output_file_id. Status: {batch.status}"
            logger.error(error_msg)
            logger.error("Batch request counts: %s", batch.request_counts)

            if batch.error_file_id:
                logger.error("Downloading error file: %s", batch.error_file_id)
                try:
                    error_file_response = self.client.files.content(batch.error_file_id)
                    error_file_path = (
                        BATCH_RESULTS_DIR / f"batch_errors_{batch.id}.jsonl"
                    )
                    error_file_path.parent.mkdir(parents=True, exist_ok=True)

                    with open(error_file_path, "w") as f:
                        f.write(error_file_response.text)

                    logger.error("Error file saved to: %s", error_file_path)

                    with open(error_file_path) as f:
                        for idx, line in enumerate(f):
                            if line.strip():
                                error_data = json.loads(line)
                                logger.error(
                                    "Error %d: %s", idx + 1, json.dumps(error_data, indent=2)
                                )

                except Exception as exc:
                    logger.error("Failed to download error file: %s", exc)

            if hasattr(batch, "errors") and batch.errors:
                logger.error("Batch errors: %s", batch.errors)

            raise RuntimeError(error_msg)

        result_file_id = batch.output_file_id
        logger.info("Downloading results from file: %s", result_file_id)
        file_response = self.client.files.content(result_file_id)

        results_dir = BATCH_RESULTS_DIR
        results_dir.mkdir(parents=True, exist_ok=True)
        results_file_path = results_dir / f"batch_results_{batch.id}.jsonl"

        with open(results_file_path, "w") as f:
            f.write(file_response.text)

        logger.info("Downloaded batch results to: %s", results_file_path)

        results: list[dict] = []
        with open(results_file_path) as f:
            for line in f:
                result = json.loads(line)

                custom_id = result["custom_id"]
                response = result["response"]

                if response["status_code"] == 200:
                    body = response["body"]
                    choice = body["choices"][0]
                    evaluation = choice["message"]["content"].strip().upper()

                    logprobs_data = choice.get("logprobs")
                    token_logprobs: list[dict] = []

                    if logprobs_data and logprobs_data.get("content"):
                        for token_info in logprobs_data["content"]:
                            token_logprobs.append(
                                {
                                    "token": token_info["token"],
                                    "logprob": token_info["logprob"],
                                    "top_logprobs": [
                                        {
                                            "token": top["token"],
                                            "logprob": top["logprob"],
                                        }
                                        for top in token_info.get("top_logprobs", [])
                                    ],
                                }
                            )

                    results.append(
                        {
                            "custom_id": custom_id,
                            "evaluation": evaluation,
                            "logprobs": token_logprobs,
                            "finish_reason": choice["finish_reason"],
                        }
                    )
                else:
                    logger.error(
                        "Request %s failed with status: %s",
                        custom_id,
                        response["status_code"],
                    )
                    results.append(
                        {
                            "custom_id": custom_id,
                            "evaluation": "PROBLEM",
                            "logprobs": [],
                            "error": response.get("error", "Unknown error"),
                        }
                    )

        return results

    def evaluate_with_batch(
        self,
        models_to_evaluate: list[str],
        json_data_path: str,
        use_subtasks: bool = False,
    ) -> None:
        """
        Evaluate models using the Batch API.

        Args:
            models_to_evaluate (list[str]): List of models to evaluate.
            json_data_path (str): Path to the JSON dataset file.
            use_subtasks (bool): Whether to use subtasks division or not.
        """
        for model_name in models_to_evaluate:
            logger.info("Starting evaluation for model: %s", model_name)

            try:
                dataset = Dataset(json_data_path)
                logger.info("Loaded %d items from dataset", len(dataset.dataset_items))

                llm_answers: list[dict] = []
                llm = MODELS[model_name](use_subtasks=use_subtasks)

                for idx, item in enumerate(dataset.dataset_items):
                    logger.info(
                        "Generating answer %d/%d with %s",
                        idx + 1,
                        len(dataset.dataset_items),
                        model_name,
                    )

                    try:
                        if use_subtasks:
                            if not isinstance(llm.llm, ChatOllama):
                                time.sleep(2.5)
                            subquestions = llm.get_subquestions(item["question"])

                            answers: list[str] = []
                            for subq in subquestions:
                                if not isinstance(llm.llm, ChatOllama):
                                    time.sleep(2.5)
                                answers.append(llm.answer_subquestion(subq, item["context"]))

                            if not isinstance(llm.llm, ChatOllama):
                                time.sleep(2.5)
                            final_answer = llm.get_final_answer(
                                item["question"], subquestions, answers
                            )

                            llm_answers.append(
                                {
                                    "question_id": idx,
                                    "question": item["question"],
                                    "subquestions": subquestions,
                                    "sub_answers": answers,
                                    "final_answer": final_answer,
                                }
                            )
                        else:
                            if not isinstance(llm.llm, ChatOllama):
                                time.sleep(2.5)
                            final_answer = llm.answer_subquestion(
                                item["question"], item["context"]
                            )

                            llm_answers.append(
                                {
                                    "question_id": idx,
                                    "question": item["question"],
                                    "final_answer": final_answer,
                                }
                            )

                    except Exception as exc:
                        logger.error("Error generating answer for question %d: %s", idx, exc)
                        llm_answers.append(
                            {
                                "question_id": idx,
                                "question": item["question"],
                                "final_answer": "ERROR",
                                "error": str(exc),
                            }
                        )

                batch_file_paths = self.create_batch_files(dataset, model_name, llm_answers)

                all_batch_results: list[dict] = []
                for batch_file_path in batch_file_paths:
                    batch_id = self.submit_batch(batch_file_path)
                    completed_batch = self.wait_for_batch_completion(batch_id)
                    batch_results = self.parse_batch_results(completed_batch)
                    all_batch_results.extend(batch_results)

                all_results: list[dict] = []
                for result in all_batch_results:
                    question_id = int(result["custom_id"].split("_q")[1])

                    all_results.append(
                        {
                            "model": model_name,
                            "question_id": question_id,
                            "question": dataset.dataset_items[question_id]["question"],
                            "answer_eval": result["evaluation"],
                            "logprobs": result["logprobs"],
                        }
                    )

                    logger.info(
                        "Model: %s, Question ID: %d, Evaluation: %s",
                        model_name,
                        question_id,
                        result["evaluation"],
                    )

                self._save_detailed_results(model_name, all_results, use_subtasks)

                logger.info("Generating visualisations")
                self.generate_pie_charts(all_results, use_subtasks)
                self.generate_bar_charts(all_results, use_subtasks)

            except Exception as exc:
                logger.error("Error evaluating model %s: %s", model_name, exc)
                raise

    def _save_detailed_results(
        self, model_name: str, results: list[dict], use_subtasks: bool = False
    ) -> None:
        """
        Save detailed results including logprobs to a JSON file.

        Args:
            model_name (str): Name of the model.
            results (list[dict]): List of evaluation results.
            use_subtasks (bool): Whether subtasks were used.
        """
        dir_path = self._output_dir(model_name, use_subtasks)
        dir_path.mkdir(parents=True, exist_ok=True)

        results_path = dir_path / "gpt_batch_evaluation_results.json"

        with open(results_path, "w") as f:
            json.dump(results, f, indent=2)

        logger.info("Saved detailed results with logprobs to: %s", results_path)
