import json
import logging
import os
import time
from pathlib import Path
from typing import Dict, List

from dotenv import load_dotenv
from langchain_ollama import ChatOllama
from openai import OpenAI

from medicalexplainer.dataset import Dataset
from medicalexplainer.evaluator import Evaluator
from medicalexplainer.llm import models
from medicalexplainer.logger import configure_logger

configure_logger(
    name="evaluator_gpt_batch",
    filepath=Path(__file__).parent / "data/evaluation/medicalexplainer.log",
)
logger = logging.getLogger("evaluator_gpt_batch")


class EvaluatorGPTBatch(Evaluator):
    """
    Evaluator that uses a batch model with OpenAI's Batch API to evaluate answers
    and obtain logprobs for YES/NO responses.
    """

    def __init__(self):
        """Initialize the batch evaluator with OpenAI client."""
        super().__init__()
        load_dotenv()
        self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        self.model = "gpt-4.1-nano"
        logger.info(f"Initialized EvaluatorGPTBatch with model: {self.model}")

    def create_evaluation_request(
        self,
        custom_id: str,
        question: str,
        answer_llm: str,
        expected_answer: str,
        context: str,
    ) -> Dict:
        """
        Create a single evaluation request in the format required by OpenAI Batch API.

        Args:
            custom_id (str): Unique identifier for this request
            question (str): The question to evaluate
            answer_llm (str): The answer generated by the LLM
            expected_answer (str): The expected answer from the dataset
            context (str): The medical context from the dataset

        Returns:
            Dict: A request object formatted for the Batch API
        """
        prompt = f"""Here is a medical question with its context and the answer that was generated by LLM:
Context: "{context}"
Question: "{question}"
Answer LLM: "{answer_llm}"
Compare it with the expected answer:
"{expected_answer}"
Is the answer generated by the LLM almost correct compared to the expected answer?
You ONLY can answer YES/NO"""

        return {
            "custom_id": custom_id,
            "method": "POST",
            "url": "/v1/chat/completions",
            "body": {
                "model": self.model,
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a medical expert evaluator. You must respond only with YES or NO.",
                    },
                    {"role": "user", "content": prompt},
                ],
                "max_tokens": 5,
                "temperature": 0,
                "logprobs": True,
                "top_logprobs": 2,
            },
        }

    def create_batch_files(
        self,
        dataset: Dataset,
        model_name: str,
        llm_answers: List[Dict],
        max_requests_per_batch: int = 200,
    ) -> List[str]:
        """
        Create JSONL files with evaluation requests, splitting into multiple batches if needed.

        Args:
            dataset (Dataset): The dataset with questions and expected answers
            model_name (str): Name of the model being evaluated
            llm_answers (List[Dict]): List of answers generated by the LLM
            max_requests_per_batch (int): Maximum requests per batch to avoid token limits

        Returns:
            List[str]: Paths to the created JSONL files
        """
        batch_dir = Path(__file__).parent / "data" / "evaluation" / "batch_requests"
        batch_dir.mkdir(parents=True, exist_ok=True)

        timestamp = int(time.time())
        total_items = len(dataset.dataset_items)
        num_batches = (
            total_items + max_requests_per_batch - 1
        ) // max_requests_per_batch

        batch_file_paths = []

        for batch_num in range(num_batches):
            start_idx = batch_num * max_requests_per_batch
            end_idx = min(start_idx + max_requests_per_batch, total_items)

            batch_file_path = (
                batch_dir
                / f"batch_{model_name}_{timestamp}_part{batch_num + 1}of{num_batches}.jsonl"
            )

            with open(batch_file_path, "w") as f:
                for idx in range(start_idx, end_idx):
                    item = dataset.dataset_items[idx]
                    llm_answer = llm_answers[idx]

                    request = self.create_evaluation_request(
                        custom_id=f"{model_name}_q{idx}",
                        question=item["question"],
                        answer_llm=llm_answer["final_answer"],
                        expected_answer=item["answer"],
                        context=item["context"],
                    )
                    f.write(json.dumps(request) + "\n")

            logger.info(
                f"Created batch file {batch_num + 1}/{num_batches}: {batch_file_path} ({end_idx - start_idx} requests)"
            )
            batch_file_paths.append(str(batch_file_path))

        return batch_file_paths

    def check_batch_capacity(self) -> bool:
        """
        Check if there are in-progress batches that might be using the token limit.

        Returns:
            bool: True if there's capacity, False if should wait
        """
        try:
            batches = self.client.batches.list(limit=10)
            in_progress = [
                b
                for b in batches.data
                if b.status in ["validating", "in_progress", "finalizing"]
            ]

            if in_progress:
                logger.warning(f"Found {len(in_progress)} batches in progress:")
                for b in in_progress:
                    logger.warning(f"  - Batch {b.id}: {b.status}")
                return False
            return True
        except Exception as e:
            logger.error(f"Error checking batch capacity: {e}")
            return True

    def submit_batch(
        self, batch_file_path: str, max_retries: int = 5, retry_delay: int = 300
    ) -> str:
        """
        Upload the batch file to OpenAI and create a batch job.
        Retries if token limit is exceeded.

        Args:
            batch_file_path (str): Path to the JSONL batch file
            max_retries (int): Maximum number of retries
            retry_delay (int): Seconds to wait between retries (default: 5 minutes)

        Returns:
            str: The batch ID
        """
        # Upload the file
        with open(batch_file_path, "rb") as f:
            batch_input_file = self.client.files.create(file=f, purpose="batch")

        logger.info(f"Uploaded batch file with ID: {batch_input_file.id}")

        # Try to create the batch with retries
        for attempt in range(max_retries):
            try:
                # Check if there are in-progress batches
                if not self.check_batch_capacity():
                    logger.warning(
                        f"Token limit may be reached. Waiting {retry_delay}s before retry {attempt + 1}/{max_retries}..."
                    )
                    time.sleep(retry_delay)
                    continue

                # Create the batch
                batch = self.client.batches.create(
                    input_file_id=batch_input_file.id,
                    endpoint="/v1/chat/completions",
                    completion_window="24h",
                )

                logger.info(f"Created batch with ID: {batch.id}")
                return batch.id

            except Exception as e:
                error_str = str(e)
                if (
                    "token_limit_exceeded" in error_str
                    or "enqueued token limit" in error_str.lower()
                ):
                    logger.warning(
                        f"Token limit exceeded. Attempt {attempt + 1}/{max_retries}. Waiting {retry_delay}s..."
                    )
                    time.sleep(retry_delay)
                else:
                    logger.error(f"Error creating batch: {e}")
                    raise

        raise Exception(
            f"Failed to create batch after {max_retries} retries due to token limit"
        )

    def wait_for_batch_completion(self, batch_id: str, poll_interval: int = 60) -> Dict:
        """
        Wait for a batch to complete, polling at regular intervals.

        Args:
            batch_id (str): The batch ID to monitor
            poll_interval (int): Seconds to wait between status checks

        Returns:
            Dict: The completed batch object
        """
        logger.info(f"Waiting for batch {batch_id} to complete...")

        while True:
            batch = self.client.batches.retrieve(batch_id)
            logger.info(f"Batch {batch_id} status: {batch.status}")

            if batch.status == "completed":
                logger.info(f"Batch {batch_id} completed successfully")
                logger.debug(f"Batch object: {batch}")
                logger.debug(f"Batch output_file_id: {batch.output_file_id}")
                logger.debug(f"Batch error_file_id: {batch.error_file_id}")
                return batch
            elif batch.status in ["failed", "expired", "cancelled"]:
                logger.error(f"Batch {batch_id} ended with status: {batch.status}")
                if hasattr(batch, "errors"):
                    logger.error(f"Batch errors: {batch.errors}")
                raise Exception(f"Batch failed with status: {batch.status}")

            time.sleep(poll_interval)

    def parse_batch_results(self, batch: Dict) -> List[Dict]:
        """
        Download and parse the results from a completed batch.

        Args:
            batch (Dict): The completed batch object

        Returns:
            List[Dict]: List of results with evaluations and logprobs
        """
        # Check if output_file_id exists
        if not batch.output_file_id:
            error_msg = (
                f"Batch {batch.id} has no output_file_id. Status: {batch.status}"
            )
            logger.error(error_msg)
            logger.error(f"Batch request counts: {batch.request_counts}")

            # Download error file if available
            if batch.error_file_id:
                logger.error(f"Downloading error file: {batch.error_file_id}")
                try:
                    error_file_response = self.client.files.content(batch.error_file_id)
                    error_file_path = (
                        Path(__file__).parent
                        / "data"
                        / "evaluation"
                        / "batch_results"
                        / f"batch_errors_{batch.id}.jsonl"
                    )
                    error_file_path.parent.mkdir(parents=True, exist_ok=True)

                    with open(error_file_path, "w") as f:
                        f.write(error_file_response.text)

                    logger.error(f"Error file saved to: {error_file_path}")

                    # Parse and log errors
                    with open(error_file_path, "r") as f:
                        for idx, line in enumerate(f):
                            if line.strip():
                                error_data = json.loads(line)
                                logger.error(
                                    f"Error {idx + 1}: {json.dumps(error_data, indent=2)}"
                                )

                except Exception as e:
                    logger.error(f"Failed to download error file: {e}")

            if hasattr(batch, "errors") and batch.errors:
                logger.error(f"Batch errors: {batch.errors}")

            raise Exception(error_msg)

        # Download the results file
        result_file_id = batch.output_file_id
        logger.info(f"Downloading results from file: {result_file_id}")
        file_response = self.client.files.content(result_file_id)

        # Save results to local file
        results_dir = Path(__file__).parent / "data" / "evaluation" / "batch_results"
        results_dir.mkdir(parents=True, exist_ok=True)
        results_file_path = results_dir / f"batch_results_{batch.id}.jsonl"

        with open(results_file_path, "w") as f:
            f.write(file_response.text)

        logger.info(f"Downloaded batch results to: {results_file_path}")

        # Parse the results
        results = []
        with open(results_file_path, "r") as f:
            for line in f:
                result = json.loads(line)

                custom_id = result["custom_id"]
                response = result["response"]

                if response["status_code"] == 200:
                    body = response["body"]
                    choice = body["choices"][0]

                    evaluation = choice["message"]["content"].strip().upper()

                    # Extract logprobs
                    logprobs_data = choice.get("logprobs")
                    token_logprobs = []

                    if logprobs_data and logprobs_data.get("content"):
                        for token_info in logprobs_data["content"]:
                            token_logprobs.append(
                                {
                                    "token": token_info["token"],
                                    "logprob": token_info["logprob"],
                                    "top_logprobs": [
                                        {
                                            "token": top["token"],
                                            "logprob": top["logprob"],
                                        }
                                        for top in token_info.get("top_logprobs", [])
                                    ],
                                }
                            )

                    results.append(
                        {
                            "custom_id": custom_id,
                            "evaluation": evaluation,
                            "logprobs": token_logprobs,
                            "finish_reason": choice["finish_reason"],
                        }
                    )
                else:
                    logger.error(
                        f"Request {custom_id} failed with status: {response['status_code']}"
                    )
                    results.append(
                        {
                            "custom_id": custom_id,
                            "evaluation": "PROBLEM",
                            "logprobs": [],
                            "error": response.get("error", "Unknown error"),
                        }
                    )

        return results

    def evaluate_with_batch(
        self, models_to_evaluate: List[str], json_data_path: str, tools: bool = False
    ) -> None:
        """
        Evaluate models using the Batch API.

        Args:
            models_to_evaluate (List[str]): List of models to evaluate
            json_data_path (str): Path to the JSON dataset file
            tools (bool): Whether to use tools or not
        """
        for model_name in models_to_evaluate:
            logger.info(f"Starting evaluation for model: {model_name}")

            try:
                # Load dataset
                dataset = Dataset(json_data_path)
                logger.info(f"Loaded {len(dataset.dataset_items)} items from dataset")

                # Generate answers with the model being evaluated
                llm_answers = []
                llm = models[model_name](tools=tools)

                for idx, item in enumerate(dataset.dataset_items):
                    logger.info(
                        f"Generating answer {idx + 1}/{len(dataset.dataset_items)} with {model_name}"
                    )

                    try:
                        # Generate sub-questions
                        if not isinstance(llm.llm, ChatOllama):
                            time.sleep(2.5)
                        subquestions = llm.get_subquestions(item["question"])

                        # Answer sub-questions
                        answers = []
                        for subq in subquestions:
                            if not isinstance(llm.llm, ChatOllama):
                                time.sleep(2.5)
                            answer = llm.answer_subquestion(subq, item["context"])
                            answers.append(answer)

                        # Get final answer
                        if not isinstance(llm.llm, ChatOllama):
                            time.sleep(2.5)
                        final_answer = llm.get_final_answer(
                            item["question"], subquestions, answers
                        )

                        llm_answers.append(
                            {
                                "question_id": idx,
                                "question": item["question"],
                                "subquestions": subquestions,
                                "sub_answers": answers,
                                "final_answer": final_answer,
                            }
                        )

                    except Exception as e:
                        logger.error(f"Error generating answer for question {idx}: {e}")
                        llm_answers.append(
                            {
                                "question_id": idx,
                                "question": item["question"],
                                "final_answer": "ERROR",
                                "error": str(e),
                            }
                        )

                # Create batch files (may split into multiple if too large)
                batch_file_paths = self.create_batch_files(
                    dataset, model_name, llm_answers
                )

                # Submit and process each batch
                all_batch_results = []
                for batch_file_path in batch_file_paths:
                    # Submit batch
                    batch_id = self.submit_batch(batch_file_path)

                    # Wait for completion
                    completed_batch = self.wait_for_batch_completion(batch_id)

                    # Parse results
                    batch_results = self.parse_batch_results(completed_batch)
                    all_batch_results.extend(batch_results)

                # Process and save results
                all_results = []
                for result in all_batch_results:
                    # Extract question ID from custom_id (format: modelname_qX)
                    question_id = int(result["custom_id"].split("_q")[1])

                    all_results.append(
                        {
                            "model": model_name,
                            "question_id": question_id,
                            "question": dataset.dataset_items[question_id]["question"],
                            "answer_eval": result["evaluation"],
                            "logprobs": result["logprobs"],
                        }
                    )

                    logger.info(
                        f"Model: {model_name}, Question ID: {question_id}, "
                        f"Evaluation: {result['evaluation']}"
                    )

                # Save detailed results with logprobs
                self._save_detailed_results(model_name, all_results, tools)

                # Generate visualizations
                logger.info("Generating visualizations")
                self.generate_pie_charts(all_results, tools)
                self.generate_bar_charts(all_results, tools)

            except Exception as e:
                logger.error(f"Error evaluating model {model_name}: {e}")
                raise

    def _save_detailed_results(
        self, model_name: str, results: List[Dict], tools: bool = False
    ) -> None:
        """
        Save detailed results including logprobs to a JSON file.

        Args:
            model_name (str): Name of the model
            results (List[Dict]): List of evaluation results
            tools (bool): Whether tools were used
        """
        dir_path = (
            f"medicalexplainer/data/evaluation/{model_name}_tools/"
            if tools
            else f"medicalexplainer/data/evaluation/{model_name}/"
        )
        os.makedirs(dir_path, exist_ok=True)

        results_path = Path(dir_path) / "gpt_batch_evaluation_results.json"

        with open(results_path, "w") as f:
            json.dump(results, f, indent=2)

        logger.info(f"Saved detailed results with logprobs to: {results_path}")
