"""
evaluator - Orchestrates the LLM evaluation loop and result visualisations.

The :class:`Evaluator` class runs each model against the medical QA dataset,
compares generated answers with expected ones via a judge LLM, and produces
pie and bar charts summarising accuracy.
"""

import logging
import time
from collections import OrderedDict, defaultdict
from pathlib import Path

import plotly.express as px
import plotly.graph_objects as go
from langchain.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_ollama import ChatOllama

from medicalexplainer.dataset import Dataset
from medicalexplainer.llm import MODELS
from medicalexplainer.logger import configure_logger
from medicalexplainer.paths import EVALUATION_DIR, LOG_PATH

logger = logging.getLogger("evaluator")


class Evaluator:
    """Evaluates LLM models on a medical QA dataset and generates result charts."""

    def __init__(self) -> None:
        configure_logger(name="evaluator", filepath=LOG_PATH)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _output_dir(model: str, use_subtasks: bool) -> Path:
        """Return the output directory path for a given model run."""
        suffix = "" if use_subtasks else "_nodiv"
        return EVALUATION_DIR / f"{model}{suffix}"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def evaluate_answer(
        self, question: str, answer_llm: str, expected_answer: str, context: str
    ) -> str:
        """
        Use a judge LLM to compare a generated answer against the expected answer.

        Args:
            question (str): The question that was asked.
            answer_llm (str): The answer generated by the model under test.
            expected_answer (str): The ground-truth answer from the dataset.
            context (str): The medical context from the dataset.

        Returns:
            str: "YES" if the answer is correct, "NO" otherwise.
        """
        template = (
            'Here is a medical question with its context and the answer that was generated by LLM:\n'
            'Context: "{context}"\n'
            'Question: "{question}"\n'
            'Answer LLM: "{answer_LLM}"\n'
            'Compare it with the expected answer:\n'
            '"{answer}"\n'
            'Is the answer generated by the LLM almost correct compared to the expected answer?\n'
            'You ONLY can answer YES/NO'
        )

        prompt = ChatPromptTemplate.from_template(template)
        judge_llm = MODELS["gpt-oss"]()

        chain = prompt | judge_llm.llm | StrOutputParser()

        answer = chain.invoke(
            {
                "context": context,
                "question": question,
                "answer_LLM": answer_llm,
                "answer": expected_answer,
            }
        )
        logger.debug(
            "Question: %s, Answer LLM: %s, Expected: %s, Comparison: %s",
            question,
            answer_llm,
            expected_answer,
            answer,
        )
        return answer

    def evaluate(
        self,
        models_to_evaluate: list[str],
        json_data_path: str,
        use_subtasks: bool = False,
        limit: int | None = None,
    ) -> None:
        """
        Evaluate models on medical questions from the JSON dataset.

        Args:
            models_to_evaluate (list[str]): List of model names to evaluate.
            json_data_path (str): Path to the JSON dataset file.
            use_subtasks (bool): Whether to use subtasks division or not.
            limit (int | None): Cap the number of questions evaluated (useful for testing).
        """
        for model in models_to_evaluate:
            all_results: list[dict] = []

            try:
                logger.debug("Loading dataset from: %s", json_data_path)
                dataset = Dataset(json_data_path)

                items = dataset.dataset_items
                if limit is not None:
                    items = items[:limit]

                logger.debug("Processing %d items with model: %s", len(items), model)

                for idx, item in enumerate(items):
                    context = item["context"]
                    question = item["question"]
                    expected_answer = item["answer"]

                    logger.debug(
                        "Processing question %d/%d: %s... with model: %s",
                        idx + 1,
                        len(items),
                        question[:50],
                        model,
                    )

                    eval_result = "PROBLEM"
                    for attempt in range(10):
                        logger.debug(
                            "Attempting question %d, attempt: %d", idx + 1, attempt + 1
                        )
                        try:
                            llm = MODELS[model](use_subtasks=use_subtasks)

                            if use_subtasks:
                                if not isinstance(llm.llm, ChatOllama):
                                    time.sleep(2.5)
                                subquestions = llm.get_subquestions(question)
                                logger.debug(
                                    "Generated %d subquestions for question %d",
                                    len(subquestions),
                                    idx + 1,
                                )

                                answers: list[str] = []
                                for subquestion in subquestions:
                                    if not isinstance(llm.llm, ChatOllama):
                                        time.sleep(2.5)
                                    answers.append(
                                        llm.answer_subquestion(subquestion, context)
                                    )

                                if not isinstance(llm.llm, ChatOllama):
                                    time.sleep(2.5)
                                final_answer = llm.get_final_answer(
                                    question, subquestions, answers
                                )
                            else:
                                if not isinstance(llm.llm, ChatOllama):
                                    time.sleep(2.5)
                                final_answer = llm.answer_subquestion(question, context)

                            try:
                                if not isinstance(llm.llm, ChatOllama):
                                    time.sleep(2)
                                eval_result = self.evaluate_answer(
                                    question, final_answer, expected_answer, context
                                )
                            except Exception as exc:
                                logger.error("Error evaluating answer: %s", exc)
                                eval_result = "PROBLEM"

                            if eval_result != "PROBLEM":
                                break

                        except Exception as exc:
                            logger.error(
                                "Error processing question %d: %s", idx + 1, exc
                            )
                            eval_result = "PROBLEM"
                            time.sleep(10)

                    all_results.append(
                        {
                            "model": model,
                            "question_id": idx,
                            "question": question,
                            "answer_eval": eval_result,
                        }
                    )

                    suffix = "" if use_subtasks else "_nodiv"
                    logger.info(
                        "Model: %s%s, Question ID: %d, Answer Eval: %s",
                        model,
                        suffix,
                        idx,
                        eval_result,
                    )

            except Exception as exc:
                logger.error("Error processing dataset with model %s: %s", model, exc)
                time.sleep(10)

            logger.debug("Generating pie charts")
            self.generate_pie_charts(all_results, use_subtasks)
            logger.debug("Generating bar charts")
            self.generate_bar_charts(all_results, use_subtasks)

    def generate_bar_charts(
        self, results: list[dict], use_subtasks: bool = False
    ) -> None:
        """
        Generate grouped bar charts showing correct/incorrect answers per question.

        Args:
            results (list[dict]): Evaluation results produced by :meth:`evaluate`.
            use_subtasks (bool): Whether subtasks were used (affects output path).
        """
        model_question_data: dict = defaultdict(
            lambda: defaultdict(lambda: {"YES": 0, "NO": 0})
        )

        for result in results:
            model = result["model"]
            question_id = result["question_id"]
            eval_result = result["answer_eval"]

            if eval_result in ("YES", "NO"):
                model_question_data[model][question_id][eval_result] += 1

        for model, questions in model_question_data.items():
            sorted_question_ids = sorted(questions.keys())

            yes_values = [questions[q_id]["YES"] for q_id in sorted_question_ids]
            no_values = [questions[q_id]["NO"] for q_id in sorted_question_ids]
            q_labels = [f"Q{q_id}" for q_id in sorted_question_ids]

            fig = go.Figure(
                data=[
                    go.Bar(
                        name="Correct (YES)",
                        x=q_labels,
                        y=yes_values,
                        marker_color="#4CAF50",
                    ),
                    go.Bar(
                        name="Incorrect (NO)",
                        x=q_labels,
                        y=no_values,
                        marker_color="#F44336",
                    ),
                ]
            )

            if use_subtasks:
                title = f"Correct and incorrect answers by question: {model}"
            else:
                title = f"Correct and incorrect answers by question: {model} (no division)"

            fig.update_layout(
                barmode="group",
                title=title,
                xaxis_title="Questions",
                yaxis_title="Count",
                legend=dict(orientation="h", yanchor="bottom", y=1.02),
                width=1200,
                height=600,
                margin=dict(t=60),
            )

            dir_path = self._output_dir(model, use_subtasks)
            dir_path.mkdir(parents=True, exist_ok=True)

            with open(dir_path / "answers.txt", "w") as f:
                f.write(f"Model: {model}\n")
                f.write("Correct and incorrect answers:\n")
                for q_id in sorted_question_ids:
                    yes_count = questions[q_id]["YES"]
                    no_count = questions[q_id]["NO"]
                    f.write(f"Question {q_id}: Correct: {yes_count}, Incorrect: {no_count}\n")
                    logger.info(
                        "Model: %s, Question %s, Correct: %d, Incorrect: %d",
                        model,
                        q_id,
                        yes_count,
                        no_count,
                    )

            fig.write_image(str(dir_path / "grouped_bar_answers.png"))

    def generate_pie_charts(
        self, results: list[dict], use_subtasks: bool = False
    ) -> None:
        """
        Generate pie charts from the evaluation results.

        Args:
            results (list[dict]): Evaluation results produced by :meth:`evaluate`.
            use_subtasks (bool): Whether subtasks were used (affects output path).
        """
        model_data: dict[str, list[str]] = defaultdict(list)
        for result in results:
            model_data[result["model"]].append(result["answer_eval"])

        for model, evaluations in model_data.items():
            counts: dict[str, int] = OrderedDict(
                [
                    ("Correct (YES)", 0),
                    ("Incorrect (NO)", 0),
                    ("Problematic (PROBLEM)", 0),
                ]
            )

            for eval_result in evaluations:
                if eval_result == "YES":
                    counts["Correct (YES)"] += 1
                elif eval_result == "NO":
                    counts["Incorrect (NO)"] += 1
                else:
                    counts["Problematic (PROBLEM)"] += 1

            total = sum(counts.values())
            if total == 0:
                continue

            labels = list(counts.keys())
            values = [round((count / total) * 100, 2) for count in counts.values()]

            if use_subtasks:
                title = f"Correct and incorrect answers: {model}"
            else:
                title = f"Correct and incorrect answers: {model} (no division)"

            fig = px.pie(
                names=labels,
                values=values,
                title=title,
                color_discrete_sequence=px.colors.qualitative.Pastel,
            )

            dir_path = self._output_dir(model, use_subtasks)
            dir_path.mkdir(parents=True, exist_ok=True)

            with open(dir_path / "answers_pie_chart.txt", "w") as f:
                f.write(f"Model: {model}\n")
                f.write("Correct and incorrect answers:\n")
                for label, value in zip(labels, values):
                    f.write(f"{label}: {value}%\n")
                    logger.info("Model: %s, %s: %s%%", model, label, value)

            fig.write_image(str(dir_path / "answers_pie_chart.png"))
